### ISSUE TITLE
how to deactivate or move the Social Media/Search - Sidebar

### ISSUE THREAD

**Issue by vvvika** [AlxMedia/clearwork#3]
Hello.
I'm a bit stuck at the moment. I have installed and activated the Clearwork theme for my personal wordpress site. Everything is fine so far. The only thing that bothers me is the narrow bar on the side that is used for social media icons and search. How can I deactivate or move it, e.g. to the footer area?
I'm sure it's something quite trivial, but I can't figure it out. 
Thanks in advance. 
![Sidebar](https://github.com/user-attachments/assets/c2c5e44e-03ff-4d73-882e-ce664b254a69)

**Comment by AlxMedia** [comment]
Hi there! Try adding this in Customize > Additional CSS:
`.sidebar.s2 { display: none; }`

**Comment by vvvika** [comment]
wow, that worked perfectly well. thank you!

**Comment by AlxMedia** [comment]
Glad to hear! :)
